project:
  type: website
  output-dir: docs


website:
  title: "Statistics for Psychologists"
  image: "Images/icon.png"
  favicon: "Images/favicon.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: PSYC121/index.qmd
        text: PSYC121
      - href: PSYC122/index.qmd
        text: PSYC122
      - href: PSYC214/index.qmd
        text: PSYC214
      - href: PSYC401/index.qmd
        text: PSYC401      
      - href: PSYC402/index.qmd
        text: PSYC402
      - href: Resources/index.qmd
        text: Resources
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "PSYC121"
        contents: PSYC121/*
      - section: "PSYC122"
        contents: PSYC122/*
      - section: "PSYC214"
        contents: PSYC214/*
      - section: "PSYC234"
        contents: PSYC234/*
      - section: "PSYC401"
        contents: PSYC401/*
      - section: "PSYC402"
        contents: PSYC402/* 
      - section: "Resources"
        contents: Resources/*  
        
        
  page-footer:
    left: "Website developed by Matthew Ivory"
    center: "Link 1"
    right: "GithubLink"

format:
  html:
    theme: 
      - default
    css: styles.css
    code-overflow: wrap
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    toc: true

editor: source