project:
  type: website
  output-dir: docs


website:
  title: "Statistics for Psychologists"
  logo: "Images/icon.png"
  favicon: "Images/favicon.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: PSYC121/Week1.qmd
        text: PSYC121
      - href: PSYC122/Week1.qmd
        text: PSYC122
      - href: PSYC214/Week1.qmd
        text: PSYC214
      - href: PSYC401/Week1.qmd
        text: PSYC401      
      - href: PSYC402/Week1.qmd
        text: PSYC402
      - href: resources.qmd
        text: Resources
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "PSYC121"
        contents:
          - PSYC121/Week1.qmd
          - PSYC121/Week2.qmd
          - PSYC121/Week3.qmd
          - PSYC121/Week4.qmd
          - PSYC121/Week5.qmd
          - PSYC121/Week6.qmd
          - PSYC121/Week7.qmd
          - PSYC121/Week8.qmd
          - PSYC121/Week9.qmd
      - section: "PSYC122"
        contents: 
          - TBC
          - TBD
          - TBE
          
  page-footer:
    left: "Website developed by Matthew Ivory"
    center: "Link 1"
    right: "GithubLink"

format:
  html:
    theme: default
    css: styles.css
    code-overflow: wrap
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    toc: true

editor: source

